### ISSUE TITLE
TrafficJunction-v0 is not working

### ISSUE THREAD

**Issue by AmulyaReddy99** [koulanurag/ma-gym#12]
Raises error as below
```
traffic_junction/traffic_junction.py", line 85, in get_agent_obs
    pos = self.agent_pos[agent_i]
KeyError: 0
```
I tried printing agent_pos which has empty dictionary {}. Checking the code, I realised agent_pos is never being updated like in other envs (Switch, Checkers etc...)

**Comment by koulanurag** [comment]
Hi @AmulyaReddy99 

Thanks for pointing it out.

Actually, environments mentioned in the [Zoo](https://github.com/koulanurag/ma-gym#zoo) are the only valid environments.

Traffic-Junction is not a working environment and the existing code is just kept there as a baseline code for me (or someone ) to work on eventually. At the same time, I felt that it will have similar dynamics as the Switch or Combat.
