### ISSUE TITLE
Terminal round of Pong Duel

### ISSUE THREAD

**Issue by NaiveRed** [koulanurag/ma-gym#15]
Hi~ Currently, the default PongDuel will terminate in the 11th round.
If the `max_round=10` means the final round, should it terminate then rather than 11?  And It will also not take the final reward into account.
Therefore, It seems that it may more straightforward to just stop in the 10th.

https://github.com/koulanurag/ma-gym/blob/master/ma_gym/envs/pong_duel/pong_duel.py#L233-L243

        # if ball is beyond paddle, initiate a new round
        if self.ball_pos[1] < 1:
            rewards = [0, self.reward]
            self.__rounds += 1
        elif self.ball_pos[1] >= (self._grid_shape[1] - 1):
            rewards = [self.reward, 0]
            self.__rounds += 1

        if self.__rounds > self._max_rounds:
            self._agent_dones = [True for _ in range(self.n_agents)]
            rewards = [0 for _ in range(self.n_agents)]

If looks good, I can submit a PR with this small change:

    if self.__rounds == self._max_rounds:
        self._agent_dones = [True for _ in range(self.n_agents)]
    else:
        ...

**Comment by koulanurag** [comment]
Hi @NaiveRed 
Yes, you are right. At the same time, it's because of round counter being started from 0.

So, I would be happy to receive PR for following change.
```
if self.__rounds == self._max_rounds:
    self._agent_dones = [True for _ in range(self.n_agents)]
else:
    ...
```

Thank you
