### ISSUE TITLE
Off by one error

### ISSUE THREAD

**Issue by aswin-raghavan** [koulanurag/ma-gym#17]
https://github.com/koulanurag/ma-gym/blob/1c94623571cb81298e8515c99fef70a2fee5df3d/ma_gym/envs/predator_prey/predator_prey.py#L118

`_agent_i_obs = [pos[0] / self._grid_shape[0], pos[1] / (self._grid_shape[1] - 1)]  # coordinates`
Should be 
`_agent_i_obs = [pos[0] / (self._grid_shape[0] - 1), pos[1] / (self._grid_shape[1] - 1)]  # coordinates`

**Comment by koulanurag** [comment]
Hi @NaiveRed ,
Thanks for finding this bug. I would be happy to receive a PR on this.

Note for others : This is a normalization factor to get the position coordinates in the range of [0,1]. In the current state, It's off by 1 which would give us position coordinates in the range of [0,0.8]. Implying, we still had one to one mapping from normalized form to actual position coordinates justifying the trainability of the agents. At the same time, it should be normalized in the correct range as suggested.
