### ISSUE TITLE
Snippet with warning about `steps_beyond_done` will be never execute.

### ISSUE THREAD

**Issue by uhlajs** [koulanurag/ma-gym#21]
`Elif` branch in [Checkers L204](https://github.com/koulanurag/ma-gym/blob/f3fe4376f3abb03436a0c2e2f7b8927142369969/ma_gym/envs/checkers/checkers.py#L204) will never be executed, because after the all agents are done the conditions for `if` branch holds.

**Comment by koulanurag** [comment]
Thanks for finding this bug.
It has been resolved for this env.
