### ISSUE TITLE
Seeding problem

### ISSUE THREAD

**Issue by uhlajs** [koulanurag/ma-gym#22]
As I have point it out in [Lumberjacks pull request](https://github.com/koulanurag/ma-gym/pull/19) there are several places where the environments use module `random` without any seeding and/or not using `self.np_random` attribute.

I will come up with a patch for this, however, what is the purpose of [Chekers L239](https://github.com/koulanurag/ma-gym/blob/f3fe4376f3abb03436a0c2e2f7b8927142369969/ma_gym/envs/checkers/checkers.py#L239)? And why the method `seed` return the variable `seed2` as well?

**Comment by koulanurag** [comment]
Again, Thanks for pointing out that unnecessary code line.

I have done some clean-up based on that.
