### ISSUE TITLE
A gym warning pops up when creating any environment

### ISSUE THREAD

**Issue by HatemSelim94** [koulanurag/ma-gym#28]
When calling **gym.make()** to create any ma-gym environment, the following warning pops up
> UserWarning: WARN: Box bound precision lowered by casting to float32  
[Warning link](https://github.com/openai/gym/blob/a5a6ae6bc0a5cfc0ff1ce9be723d59593c165022/gym/spaces/box.py#L61)

I have created a pull request #29  to avoid this warning.

Thank you.

**Comment by koulanurag** [comment]
Thanks for the pull request!
