### ISSUE TITLE
TrafficJunction: agent observation coordinates calculated inconsistently

### ISSUE THREAD

**Issue by joosephook** [koulanurag/ma-gym#37]
https://github.com/koulanurag/ma-gym/blob/49b7753e7e350cbc4212db58ffb19bc148d9c5e1/ma_gym/envs/traffic_junction/traffic_junction.py#L232

For example, with a grid size of `(7,7)` and an agent's position `(6,6)` this yields `[6/7,1]`.
Is there a reason for treating the `x`-coordinate differently? Or is it a bug?

**Comment by koulanurag** [comment]
Hi, @joosephook,

Thanks for finding this issue.  It should be `(self._grid_shape[0]-1)` for the purpose of standardization. At the same time, it's only a normalization factor and by the time it remains constant for all observations, it wouldn't have any effect on the dynamics of the environment.

Nevertheless, I have reduced the normalization factor by 1.

Also, the edge case of (6,6) agent position wouldn't occur in our grid for a (7,7) grid shape.


Thanks again for finding this inconsistency.

**Comment by joosephook** [comment]
Hi @koulanurag,

Glad you found it useful. I found it as I was implementing an (even) harder version of TrafficJunction and the special treatment of one matrix coordinate felt off.

Of course the specific example wouldn't occur, but it is better to be consistent, even if it is for the sake of some other person using the library and wondering why the observations seem to be slightly off when compared to, for example, raw agent positions :- )
