### ISSUE TITLE
Adjusting field of view for Predator and Prey 

### ISSUE THREAD

**Issue by richielo** [koulanurag/ma-gym#42]
Is it possible to add the capability of adjusting the field of view for the agents? I find the current 5x5 view to be too big and naively changing that parameter would break the code. Thanks!

**Comment by koulanurag** [comment]
You can refer [here](https://github.com/koulanurag/ma-gym/wiki/Usage#customizing-an-environment) and [here](https://github.com/koulanurag/ma-gym/blob/master/ma_gym/__init__.py#L63) for information on customizing an environment.

After this , you can probably create a new env with your required mask configuration.

For example:
```
import gym

# This will create a replica of `PredatorPrey7x7-v0` with `2x2` mask
gym.envs.register(
    id='PredatorPrey7x7_2X2mask-v0',
    entry_point='ma_gym.envs.predator_prey:PredatorPrey',
    kwargs={'grid_shape': (7, 7), 'n_agents': 2, 'n_preys': 1, 'agent_view_mask': (2, 2)}
)

env = gym.make('PredatorPrey7x7_2X2mask-v0')

```

**Comment by richielo** [comment]
Thank you!
