### ISSUE TITLE
AttributeError: 'PredatorPrey' object has no attribute '_base_img'

### ISSUE THREAD

**Issue by FailedMesh** [koulanurag/ma-gym#44]
![image](https://user-images.githubusercontent.com/68490344/173995586-09b3dc45-4efd-4290-8237-fcea1a719914.png)

**Comment by koulanurag** [comment]
Hi @FailedMesh 
Thanks for raising this issue. You need to call `env.reset()` before calling `env.render()`

**Comment by FailedMesh** [comment]
Thanks for the feedback!
