### ISSUE TITLE
warning when make gym environment 

### ISSUE THREAD

**Issue by charjiaman** [koulanurag/ma-gym#47]
Thank you very much for creating the environment.
However, I am having the following warnings. Is there anything I should update?
Thanks

>>> env=gym.make('Checkers-v0')
envs\marl\lib\site-packages\gym\logger.py:34: UserWarning: ←[33mWARN: Box bound precision lowered by casting to float32←[0m
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))

**Comment by koulanurag** [comment]
Thanks for your interest in the environments.

The warning is raised by the required gym version `(gym>=0.19.0,<=0.20.0)` and can be safely ignored. 

Upgrading to latest gym version ( `gym== 0.26.2`) leads to some compatibility issues as of now. In future; I would be upgrading `ma-gym` to the latest gym version or I am happy to take a PR for the same :)

**Comment by charjiaman** [comment]
Thank you for the explanation!
