### ISSUE TITLE
'EnvSpec' object has no attribute '_kwargs', why does the usage code not work?

### ISSUE THREAD

**Issue by TryingToMakeDo** [koulanurag/ma-gym#48]
Hello, whenever I try to use ma-gym to create a multiagent environment in Colab it always gives the same error:

>[/content/ma-gym/ma_gym/__init__.py](https://localhost:8080/#) in <module>
>    13         id='ma_' + spec.id,
>    14         entry_point='ma_gym.envs.openai:MultiAgentWrapper',
>---> 15         kwargs={'name': spec.id, **spec._kwargs}
>    16     )
>    17 

>AttributeError: 'EnvSpec' object has no attribute '_kwargs'

I'm trying to run the following:

>import gym
>env = gym.make('ma_gym:Switch2-v0')
>done_n = [False for _ in range(env.n_agents)]
>ep_reward = 0

>obs_n = env.reset()
>while not all(done_n):
>   env.render()
>   obs_n, reward_n, done_n, info = env.step(env.action_space.sample())
>   ep_reward += sum(reward_n)
>env.close()

I'm new to all of this so sorry if this doesn't meet the standards of an issue.

**Comment by TryingToMakeDo** [comment]
After countless searches I fixed it, you need setuptools==66, wheel==0.38.4, gym==0.19. All can be pip installed on colab.

**Comment by koulanurag** [comment]
Thanks for raising this issue and sharing the answer.

Based on your feedback, I have added an example file in the repo.
