### ISSUE TITLE
Feature request: Provide observation_space property using gym objects in MA environments

### ISSUE THREAD

**Issue by akharitonov** [koulanurag/ma-gym#5]
Code, which is written with Gym in mind often expects both action spaces and observation spaces provided upon the creation of the environment.

An example of the `observation_space` can be seen in the classic [Atari environment](https://github.com/openai/gym/blob/c33cfd8b2cc8cac6c346bc2182cd568ef33b8821/gym/envs/atari/atari_env.py#L77) of gym. 

Without it, the library can't be used with frameworks such as [Ray RLLib](https://ray.readthedocs.io/en/latest/rllib.html). It explicitly requires both action spaces and observation spaces to be provided in policies. 

Therefore, if someone wants to use ma-gym with ray, observation spaces dictionaries must be deduced and constructed manually.

**Comment by hzyjerry** [comment]
Agreed, would be nice to have `observation_space`

**Comment by hzyjerry** [comment]
I opened up a PR with implementations of observation_space. The functionalities are all tested, please take a look :) 
https://github.com/koulanurag/ma-gym/pull/6/files

**Comment by koulanurag** [comment]
@akharitonov  Thanks for the suggestion. It sounds like a nice addition to the repo.
I usually used to do ```env.reset()``` to get the observation shape. But, having the observation_space attribute could further help with the normalization.

@hzyjerry  Thanks for the interest and  doing the required changes. I would look into your pull request and will accept it :)

At the same time, despite these changes, I feel we would always need some form of wrapper for RLLib as discussed over [here](https://www.reddit.com/r/MachineLearning/comments/crs3ye/r_magym_multi_agent_environments_based_on_open_ai/).

Happy to receive further suggestions over this!
