### ISSUE TITLE
__init__.py error

### ISSUE THREAD

**Issue by SonnyHM** [koulanurag/ma-gym#50]
Hello.
 I'm trying to execute the code in colab 
which is https://colab.research.google.com/github/matteokarldonati/Counterfactual-Multi-Agent-Policy-Gradients/blob/master/COMA.ipynb#scrollTo=cvdZvb-V6d63

But there is an error in the __init__.py like below 

<img width="628" alt="Screenshot 2023-05-28 at 5 03 15 PM" src="https://github.com/koulanurag/ma-gym/assets/126227841/aa5c1d5b-51ad-4d80-9df4-0de36a424b24">
<img width="718" alt="Screenshot 2023-05-28 at 5 03 23 PM" src="https://github.com/koulanurag/ma-gym/assets/126227841/3704542c-f748-49eb-a125-6f257178ec32">

<img width="921" alt="Screenshot 2023-05-28 at 5 03 31 PM" src="https://github.com/koulanurag/ma-gym/assets/126227841/771dbbc7-1b61-472b-b5c3-159e9f333bea">
2d6-422a-a1f7-5cc321c5bb2a">

Do you know what's the problem with it?? 
Thank you.

**Comment by koulanurag** [comment]
You can follow colab instructions over [here](https://colab.research.google.com/github/koulanurag/ma-gym/blob/master/examples/colab_example.ipynb).

This is primarily due to `pip` ,` setuptools` and `wheel` versions.
