### ISSUE TITLE
About the number of agents in switch environment

### ISSUE THREAD

**Issue by SonnyHM** [koulanurag/ma-gym#52]
Hi, I actively use your ma-gym. Thank you.
I have a question about the number of agents in switch environment.
If I choose the 'switch2-vo' environment, then the number of agents set to 2 automatically? 
Or do I have to revise the number of agents in the switch_one_corridor.py file? 
Thank you. :)

**Comment by koulanurag** [comment]
Thanks for your interest in this repo.

Yes, the default number of agents in "Switch2" is 2 and "Switch4" contains 4 agents. You can find more details of Switch environment over here https://github.com/koulanurag/ma-gym/wiki/Environments#Switch .

If you would like to customize and create new version of this environment , I would recommend referring to https://github.com/koulanurag/ma-gym/wiki/Usage#customizing-an-environment
