### ISSUE TITLE
Switch2-v0

### ISSUE THREAD

**Issue by SonnyHM** [koulanurag/ma-gym#53]
Hello. 
I want to ask about the reward in switch2-v0. 
The reward for agents is coming out as [-0.1, -0.1], but when I looked at the environment code, it seems there is no reason for it to output like this. Do you know Why is this happening?
Thank you :)

**Comment by koulanurag** [comment]
Environment returns local reward for each agent.

You can refer [https://github.com/koulanurag/ma-gym/wiki/Usage#Basics](https://github.com/koulanurag/ma-gym/wiki/Usage#Basics) for more details on usage.
